-- Criar uma trigger ao inserir ou atualizar um controle 
DROP TRIGGER IF EXISTS TGR_MC_NotaFiscal_Mensagem
GO
CREATE TRIGGER TGR_MC_NotaFiscal_Mensagem
ON MC_NotaFiscal_Mensagem
AFTER INSERT, UPDATE, DELETE
AS 
BEGIN

	DECLARE 
			@IND_TIPO_CMD NVARCHAR(1) = 'I',
			@ID_USUARIO BIGINT,
			@DSC_USUARIO NVARCHAR(100),
			@ID_EMPRESA BIGINT,
			@DAT_REG_OPER DATETIME = GETDATE(),
			@NOM_TABELA VARCHAR(100) = 'MC_NOTAFISCAL_MENSAGEM',
			@DSC_CMD NVARCHAR(4000),
			@IP_MAQ VARCHAR(15) = Convert(varchar,CONNECTIONPROPERTY('client_net_address'))
	
	IF EXISTS(Select * from DELETED)
	BEGIN
		SET @IND_TIPO_CMD = CASE WHEN EXISTS(SELECT * FROM INSERTED) THEN 'U' ELSE 'D' END
    END
	ELSE
	BEGIN
		SET @IND_TIPO_CMD = 'I'
	END

	IF(@IND_TIPO_CMD = 'I')
	BEGIN
		SELECT 
				@ID_USUARIO = ID_USUR_ATLZ_NF,
				@DSC_USUARIO = (SELECT DISTINCT TOP 1 NOME_USUR FROM MC_Usuarios WHERE ID_USUR = ID_USUR_ATLZ_NF),
				@ID_EMPRESA = ID_EMPR,
				@DSC_CMD = CONCAT(DSC_NF_MENSAGEM,' || ','STATUS COMPRA:',(SELECT CASE WHEN STATUS_COMPRA = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),' || ', 'STATUS VENDA:',(SELECT CASE WHEN STATUS_VENDA = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),
						   ' || ', 'STATUS NFE:',(SELECT CASE WHEN STATUS_NFE = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),' || ','STATUS NFSE:',(SELECT CASE WHEN STATUS_NFSE  = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END))	
		from INSERTED 
	
		insert into mc_log(IND_TIPO_CMD,ID_USUARIO,DSC_USUARIO,ID_EMPRESA,DAT_REG_OPER,NOM_TABELA,DSC_CMD,IP_MAQ)
		select @IND_TIPO_CMD,@ID_USUARIO,@DSC_USUARIO,@ID_EMPRESA,@DAT_REG_OPER,@NOM_TABELA,@DSC_CMD,@IP_MAQ
	END

	ELSE IF(@IND_TIPO_CMD = 'U')
	BEGIN
		SELECT 
				@ID_USUARIO = ID_USUR_ATLZ_NF,
				@DSC_USUARIO = (SELECT DISTINCT TOP 1 NOME_USUR FROM MC_Usuarios WHERE ID_USUR = ID_USUR_ATLZ_NF),
				@ID_EMPRESA = ID_EMPR,
				@DSC_CMD = CONCAT(DSC_NF_MENSAGEM,' || ','STATUS COMPRA:',(SELECT CASE WHEN STATUS_COMPRA = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),' || ', 'STATUS VENDA:',(SELECT CASE WHEN STATUS_VENDA = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),
						   ' || ', 'STATUS NFE:',(SELECT CASE WHEN STATUS_NFE = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),' || ','STATUS NFSE:',(SELECT CASE WHEN STATUS_NFSE  = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END))	
		from INSERTED 
	
		insert into mc_log(IND_TIPO_CMD,ID_USUARIO,DSC_USUARIO,ID_EMPRESA,DAT_REG_OPER,NOM_TABELA,DSC_CMD,IP_MAQ)
		select @IND_TIPO_CMD,@ID_USUARIO,@DSC_USUARIO,@ID_EMPRESA,@DAT_REG_OPER,@NOM_TABELA,@DSC_CMD,@IP_MAQ
	END

	ELSE IF(@IND_TIPO_CMD = 'D')
	BEGIN
		SELECT 
				@ID_USUARIO = ID_USUR_ATLZ_NF,
				@DSC_USUARIO = (SELECT DISTINCT TOP 1 NOME_USUR FROM MC_Usuarios WHERE ID_USUR = ID_USUR_ATLZ_NF),
				@ID_EMPRESA = ID_EMPR,
				@DSC_CMD = CONCAT(DSC_NF_MENSAGEM,' || ','STATUS COMPRA:',(SELECT CASE WHEN STATUS_COMPRA = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),' || ', 'STATUS VENDA:',(SELECT CASE WHEN STATUS_VENDA = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),
						   ' || ', 'STATUS NFE:',(SELECT CASE WHEN STATUS_NFE = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END),' || ','STATUS NFSE:',(SELECT CASE WHEN STATUS_NFSE  = 1 THEN 'VERDADEIRO' ELSE 'FALSO' END))	
		from DELETED 
	
		insert into mc_log(IND_TIPO_CMD,ID_USUARIO,DSC_USUARIO,ID_EMPRESA,DAT_REG_OPER,NOM_TABELA,DSC_CMD,IP_MAQ)
		select @IND_TIPO_CMD,@ID_USUARIO,@DSC_USUARIO,@ID_EMPRESA,@DAT_REG_OPER,@NOM_TABELA,@DSC_CMD,@IP_MAQ
	END
	
END

