SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ForumTopicoAvaliador](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IdForumTopico] [int] NOT NULL UNIQUE,
	[IdUsuario] [int] NULL,
	[NomeAvaliador] [varchar](150) NULL,
	[DataAvaliador] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ForumTopicoAvaliador] ADD  DEFAULT (NULL) FOR [DataAvaliador]
GO

ALTER TABLE [dbo].[ForumTopicoAvaliador]  WITH CHECK ADD FOREIGN KEY([IdForumTopico])
REFERENCES [dbo].[ForumTopico] ([Id])
ON DELETE CASCADE


